apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- tpl .Values.customMetadata.annotations . | nindent 4 }}
  labels: {{- toYaml .Values.customMetadata.labels | nindent 4 }}
  namespace: {{ .Values.customMetadata.namespace }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Values.targetEnv }}-svc
spec:
  selector:
    {{- toYaml .Values.customMetadata.labels | nindent 4 }}
  ports:
  - name: {{ .Values.serviceSpec.name }}-{{ .Values.serviceSpec.port }}
    protocol: TCP
    port: {{ .Values.serviceSpec.port }}
    targetPort: {{ .Values.containerSpec.port }}
    {{- if .Values.serviceSpec.nodePort.enabled }}
    nodePort: {{ .Values.serviceSpec.nodePort.nodePort }}
    {{- end }}
  {{- if .Values.serviceSpec.nodePort.enabled }}
  type: {{ .Values.serviceSpec.nodePort.type }}
  {{- else if .Values.serviceSpec.loadBalancer.enabled }}
  type: LoadBalancer
  {{- end }}